### ISSUE TITLE
Example on the readme points to an unknown page

### ISSUE THREAD

**Issue by mauro-balades** [Draco-lang/Language-suggestions#113]
https://github.com/Draco-lang/Language-suggestions/blob/main/Example.fr

![Screenshot_20230408_002337](https://user-images.githubusercontent.com/91018726/230686184-8ff286ad-4faa-4b7f-ab92-567b440524d3.png)

**Comment by jakubbinter** [comment]
Thanks for the catch, actual samples are here https://github.com/Draco-lang/Language-suggestions/tree/main/Samples, i will quickly create a PR to update the readme.
