### ISSUE TITLE
Semicolon and brace significance

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Language-suggestions#27]
Following up #25 , the purpose of `{ }` and `;` came up.

### Keeping semicolons and blocks

One idea was to have it similar to OCaml/F#/Rust, and `;` would essentially chain statements, and a block would evaluate the last expression without a semicolon at the end. Example:
```
val a = {
    f();
    g();
    12 * 2
};
// 'a' is now 24
```
This would be essentially identical to
```
f();
g();
val a = 12 * 2;
```
The only difference is the extra lexical scope introduced.

I'm really not against this syntax. The braces for block are fairly familiar. Not needing semicolon for returned expressions would mean that (again, based on #25 ) the if-expression example could reduce to:
```
var a = if x() then y() else z(); // last semicolon terminating assignment
```

### Not keeping semicolons or blocks, newline and indentation significance

Other languages require less punctuation or none at all in this regard. That usually means that either whitespace or newlines are significant to aid parsing.

I'm not a fan of dropping them, as some punctuation does give a little visual aid. Again, I'm open for discussions about this.

**Comment by Sintrastes** [comment]
Honestly, after playing around with Scala 3's experimental whitespace sensitive syntax for awhile, for languages with an otherwise mainstream syntax (e.x. function keyword followed by paranthesized list of arguments to define a function, and required type annotations for function parameters), having that whitespace sensitivity just looks *off* to me. It's like an odd mixture of busy (visually) and non-busy.

**Comment by Sintrastes** [comment]
I would say that (required) semicolons I'm not a fan of. For one thing, with newlines, it's redundant. And I don't think it adds anything to readability like (arguably) braces do.

**Comment by yamin8000** [comment]
I think blocks should be defined with something like braces (` { } `) instead of whitespace or python's indentation kerfuffle and yes semicolons are relics of the past and redundant.
