### ISSUE TITLE
Explicit declaration of types

### ISSUE THREAD

**Issue by WhiteBlackGoose** [Draco-lang/Language-suggestions#28]
Sometimes you want to specify
- Type of local variable
- Type of argument
- Return type

Consider 3 ways.

## C's declaration

Type, identifier:

```
Type localVar
Type arg
Type function(...)
```

## ML, partially Pascal

Entity, colon, type
```
let localVar : Type
arg : Type
function(...) : Type
```

## VB.NET's As

```vb
Dim localVar As Type
arg As Type
function(...) As Type
```

## Of

```
val localVar of Type
arg of Type
function(...) of Type
```

That could also unify generics, like
```
type List of T
```

**Comment by LPeter1997** [comment]
I think that leading types (what C does) complicates parsing and looking at it from an outsiders eyes, it's a bit obscure (thinking of the function definition syntax mainly).

`name : type` has been getting a lot of popularity recently in more mainstream languages (Kotlin, Rust, Swift) and I really like the syntax. Some IDEs/extensions display inferred types like this even for languages like Java or C#.

I'm not against a keyword here, the idea of  `of` and combining it with generics is kinda exciting. If we decide to go with #22 , I'd say it's a better choice than `:`.
