### ISSUE TITLE
Inequality sign syntax

### ISSUE THREAD

**Issue by WhiteBlackGoose** [Draco-lang/Language-suggestions#35]
We have three options.

### Option 1: !=
Most popular operator in mainstream languages, no need to familirize anyone with it.

Becomes inconsistent with `not` operator if it's not `!`.

### Option 2: <>
Pascal and ML-famility use it. Looks a bit more mathy.

Not formally correct though, `<>` reads as less or greater, which means that operands have to have total ordering defined.

### Option 3: =/=
The closest equivalent to `≠`, but also the most verbose and least familiar.

### Vote
👍  for `!=`
🚀 for `<>`
🎉 for `=/=`

Feel free to suggest other options

**Comment by WhiteBlackGoose** [comment]
I'm voting for `!=` as there's no sane way to replace the inequality operator in the most "correct" way, so in my opinion, we should just stick with the most popular option. I'm fine with having an exceptional syntax for such a commonly used operator.

**Comment by LPeter1997** [comment]
I'm voting for `!=` for the exact reasons @WhiteBlackGoose laid out. I've also voted for `=/=`, as it is a nice visual representation and I recognize the small inconsistencies `!=` introduces.

**Comment by nonamescm** [comment]
I think `!=` is the best option, both for readability and familiarity.  If the primary target is the CLR, it should be easy for C# developers to learn the basics. After all they're probably going to be the main users of this language.
