### ISSUE TITLE
Deciding new language name

### ISSUE THREAD

**Issue by jakubbinter** [Draco-lang/Language-suggestions#81]
Because the name `Fresh` is not really original, we decided that we will be voting new name for the language. This vote is not going to 100% decide what the name is going to be, it will just show us what people think about different names. In few next comments i will write the names that were proposed, if you like the name give it thumbs up(👍) if you really dislike some name give it thumbs down(👎), you can vote for as many names as you want. If you have idea on good name for the language please leave a comment with the proposed name. Please don't write random comments, so we don't spam this issue.

**Comment by jakubbinter** [comment]
Fris

**Comment by jakubbinter** [comment]
Spark

**Comment by jakubbinter** [comment]
Draco - because who doesn't like dragons?

**Comment by jakubbinter** [comment]
Phrog

**Comment by jakubbinter** [comment]
Squint

**Comment by jakubbinter** [comment]
Ketu - lang

**Comment by jakubbinter** [comment]
Geese

**Comment by jakubbinter** [comment]
Goose#

**Comment by jakubbinter** [comment]
Egg

**Comment by LPeter1997** [comment]
Dragonne

**Comment by LPeter1997** [comment]
Forge

**Comment by StarlkYT** [comment]
> Forge

There is a popular Minecraft project that provides modding APIs called Forge; I believe naming the project Forge might cause confusion.

**Comment by nonamescm** [comment]
Fresco

**Comment by Happypig375** [comment]
> Dragonne

Dragonne DEEZ NUTS ON YO FACE

(sorry)

**Comment by rikashore** [comment]
Aranea (Latin for spider, indirectly correlated to web -> network -> dotnet)

**Comment by rikashore** [comment]
Facilis (Latin for easy, correlates to the easy to grasp nature of the language)

**Comment by Kuinox** [comment]
Fresh

**Comment by Kuinox** [comment]
Drago

**Comment by LPeter1997** [comment]
Thank you so much for @jakubbinter for organizing the voting and coming up with the new name! Also, thank you everyone else who voted or suggested a name.
