### ISSUE TITLE
Start uploading code samples to the repo from the Discord server

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Language-suggestions#88]
On the Discord server we have started accumulating snippets to demonstrate the language. I believe the simpler ones could be uploaded here to provide more code samples for newcomers.

**Comment by thinker227** [comment]
The current sampels from the server are the following:

- Truth-machine
- Recursive-Fibonacci
- Quine
- Modular arithmetic
- Bare-bones TODO API controller
- Bare-bones TODO Minimal API controller
- Bare-bones TODO API controller with a custom ASP.NET wrapper
- Fizz Buzz
- Fizz Buzz with Pattern Matching
- Type hinting and casting example
- 99 bottles of beer

Which of these should we actually include? Some like the truth machine, recursive Fibonacci, Fizz Buzz / with pattern matching, and 99 Bottles of Beer demonstrate simple and practical usage of the language, while ones like modular arithmetic doesn't do a very good job of appearing as something you'd use in practice. The TODO API samples are great but I'm wondering if they're a little too advanced for this purpose, granted you mention only including the "simpler ones".

**Comment by LPeter1997** [comment]
I'd agree, let's keep the simple ones - meaning the API samples should be excluded. The modular arithmetic one is debatable, its purpose is to showcase the type system and operators more than anything else.

**Comment by thinker227** [comment]
The question is who these samples should be directed towards and what their purpose is, to showcase the language and all its features, or examples of how to practically use it? The modular arithmetic example does a good job of demonstrating that feature, but the code itself is not something you'd use in practice.

**Comment by LPeter1997** [comment]
I'd say the purpose can be both, they are samples of the language in a repo where we write the language specification.
