### ISSUE TITLE
Choosing a license

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Language-suggestions#91]
Since this is repository contains the specification for the language, we should start thinking about a license. If you are unfamiliar with software licensing, [here is a good summary](https://choosealicense.com/) of some of the most popular options.

Personally, I'd want the specs to:
 * Stay free forever
 * Make it impossible to ever close off sources, meaning that if someone forks the specs and modifies it, keep it open-source or at least make modifications public. This shouldn't apply to derivative work, that uses the specs to implement something (see below).

This yells GPL, but that is a little too invasive, because it requires derivative work to stay under the same license. If another compiler team for another language wants to be interopable with us, they'd have to read our specs, making their work technically derivative work, meaning we are enforcing GPL on them as well.

Any ideas for licensing that could fix this but keep original goals? What we need is allow certain kinds of derivative work do be relicensed, but that is hard to put into a license without being a lawyer.

**Comment by WhiteBlackGoose** [comment]
> Make it impossible to ever close off sources

Of the project, or of the project *and* all its derivatives?

**Comment by LPeter1997** [comment]
@WhiteBlackGoose I was pretty vague, elaborated a bit in the top post.

**Comment by LPeter1997** [comment]
Tried to collect my thoughts about the license a bit better. Here by "derivative work" I mean a project using knowledge from the specs, not basing their own specifications completely on our work. Interop efforts count as "derivative work". I'd like that:
 - The specs stays free forever
 - If someone copies the specs, they should keep it open source
 - If someone copies the specs and starts modifying it, it should at least make the modifications publicly available
 - If someone does derivative work of the specs, like implementing a compiler based on it, that can be considered it's own separate entity with its own licensing, but should include somewhere that they base parts of their work based on the specs
 - Not enforce derivative work to have the same license
